### ISSUE TITLE
希望能有標點居中的 CL 版

### ISSUE THREAD

**Issue by ososoio** [ChiuMing-Neko/ChiuKongGothic#14]
首先非常感謝作者的工作！

想問下能否另外製作釋出標點居中的舊字形版本呢？

工作量應該不大吧。（我不熟悉字體開發）

感謝

**Comment by ChiuMing-Neko** [comment]
工作量相較核對漢字字形及修改字圖來説確實不大，但為了單獨釋出「標點置中」的分流版實屬沒必要，因為除了增加兩倍構建時間以外，還要專門修改feature文件及對應的字型name表，總體而言相當於多了兩倍的麻煩。同時現時非漢字範圍之外的字符亦非本專案當前主要負責範圍，故暫時不考慮釋出修改成「標點置中」的分流版本。但對於以後是否會將默認分流版本中的標點符號調整成置中版本，確實値得考慮一下。

但這並不代表以後用不上修改成標點置中的版本了，現在是等把1.240版本（暫定版本號）的所需要加入的新字圖及默認字圖整理的範圍完成後，會重寫現時用來生成字型的代碼並公開釋出及有關構建字型的命令行，以方便日後使用者可根據自己的需求生成除去本專案的默認字圖版本的字型檔案。相信這個改動完成後想自行生成「標點置中」的字型檔案的情況下，只要配合修改一下字圖映射文件(C-Map)及相關OpenType feature文件（可參考思源黑體香港分流版的feature文件）就能生成了。

當然如果很着急的話，實際上標點符號也是可以先用SVS將就一下就是了（註：標點置中變體的選擇符是U+FE01）。

**Comment by ososoio** [comment]
好的。感謝答覆。

**Comment by ChiuMing-Neko** [comment]
> 能否另外製作釋出標點居中的舊字形版本呢？

基於本專案其字形風格或更加適合於傳統漢字（ **註：** 這裏指的是大致遵循傳承下來的正體字擇字習慣，而該「正體字」概念是相對「俗字」而言而非基於簡化字總表中「簡化字」所對應的「繁體字」）場景下使用，且考慮到仍在遵循「傳統」用字習慣的地區多數於排版時將標點符號置於中間，本專案若繼續使用原本的日本式標點符號或會對遵循「傳統」用字習慣的使用者造成一些困擾，因此考慮於即將釋出的1.300正式版（及第二個1.300預覽版）作出相應的調整。

對於其他標點符號位置需求，本專案當前維護的默認分流版或會在之後的版本添加相應的OpenType特性提供切換選擇，不過這仍須在重寫直接用於生成字體的代碼工作完成之後才能進行相關工作。而在正式整合相關OpenType特性之前可繼續使用異體選擇符選擇其變體。

**註：** 「傳統」用字習慣僅為粗略指代，因為實際上不少用字並不符合活字印刷時期的用字習慣。換句話説即是僅使用大五碼範圍內字符的用字習慣或通俗説法中的繁體中文。

> 現在是等把1.240版本（暫定版本號）的所需要加入的新字圖及默認字圖整理的範圍完成後，會重寫現時用來生成字型的代碼並公開釋出及有關構建字型的命令行

原本預計在1.300版正式釋出時一併釋出相關代碼，現今因相關代碼仍未完成故推遲到1.310版（內容暫定為「常用科學用字及大五碼第一字面少量異體字字圖補充」）。

**Comment by ChiuMing-Neko** [comment]
1.300已正式發佈，相關標點符號位置已作出調整。
![圖片](https://user-images.githubusercontent.com/84143394/195813461-79ac1758-8e5d-45a8-a112-4b1729135267.png)

**Comment by Tseing** [comment]
感谢作者的工作。

我主要使用该字体作为移动设备的显示字体，在横排文本环境下居中的标点显得比较突兀，在这方面确实有些众口难调。我检查了仓库文件，推测只用修改 map 文件即可改回沉底的标点。苦于我没有字体开发的经验，请问作者能否给出构建字体所使用的脚本，告诉我大致的构建流程。
