### ISSUE TITLE
错误码位

### ISSUE THREAD

**Issue by NightFurySL2001** [ChiuMing-Neko/ChiuKongGothic#16]
https://github.com/ChiuMing-Neko/ChiuKongGothic/blob/pre-1.300-workfile/Other/new_glyphs.csv#L1090

“瘟” 的 uni7601-CM 应该是 uni761F-CM。

**Comment by ChiuMing-Neko** [comment]
Fixed and the change will be pushed in the next commit (ETA this upcoming Saturday or Sunday), but normally that column is not as important as 'Unicode', 'IVS', and '默認字圖' columns.

**Comment by ChiuMing-Neko** [comment]
pushed
Ref@https://github.com/ChiuMing-Neko/ChiuKongGothic/commit/86550bdd56df91a47c209b435dada74bd2f20ca4
