### ISSUE TITLE
CL的青旁是不是有点不统一？

### ISSUE THREAD

**Issue by silascript** [ChiuMing-Neko/ChiuKongGothic#21]
![秋空_青旁](https://user-images.githubusercontent.com/13313323/230128620-20ed4657-d2a0-4686-aafd-4ad2d1cdeddf.png)

「青」和「清」这两个常用度这么高的，竟然不是「円」底？是漏了还是故意为之？

**Comment by ChiuMing-Neko** [comment]
您好，請在提交issue之前詳細閲讀readme.md中的要求，謝謝合作。

> 「青」和「清」这两个常用度这么高的

基於本專案的兼用於異體字排版的角度來説，請使用「靑」與「淸」。
