### ISSUE TITLE
ChiuKong Gothic CM 搧 沒有統一寫法

### ISSUE THREAD

**Issue by jisbig5** [ChiuMing-Neko/ChiuKongGothic#22]
ChiuKong Gothic CM 搧 沒有統一寫法 感謝作者的努力

**Comment by jisbig5** [comment]
ChiuKong Gothic CM 瘉 沒有跟 癒 統一寫法

**Comment by jisbig5** [comment]
ChiuKong Gothic CM 建議將 臉改回原寫法

**Comment by ChiuMing-Neko** [comment]
CM版於1.220版本起不再維護，你可以看到自1.220版本起沒有任何CM版的分流版釋出，亦意味着沒有包含任何自1.220版本之後才新增的新字圖。

不過倒是可以説一下CM版的默認字圖字形規則，其略字化字形僅適用於常用字範圍內，而對於非常用字範圍或「正體字」的寫法維持明朝體活字字形不變。

> 搧

通「扇」，不屬於CM版中的「常用字」，因此保留明朝體活字字形不變。

> 瘉

CM版用「癒」，所以「癒」使用了手寫體化寫法而「瘉」保留保留明朝體活字字形不變。

> 臉

CM版常用字範圍內使用略字「㑒」形
