### ISSUE TITLE
望能提供笔画分离源文件

### ISSUE THREAD

**Issue by NightFurySL2001** [ChiuMing-Neko/ChiuKongGothic#3]
您好，希望本开源项目能够提供源文件以方便后人修改（比如笔画分离ps档和其他afdko使用的文件）。先此致谢。

**Comment by ChiuMing-Neko** [comment]
筆画分離档案近期還没有釋出的計劃，可考慮未来以可変字体的形式釋出。
其他afdko使用的文件，利用現有的档案應該不難生成出来。

**Comment by NightFurySL2001** [comment]
Ok，但是仍旧希望能够单独发布笔画分离ps档以方便改作使用。

**Comment by NightFurySL2001** [comment]
P/S: 如何制作可变字体可参考已询问issue：https://github.com/adobe-fonts/source-han-sans/issues/297

**Comment by ChiuMing-Neko** [comment]
> 
> 
> Ok，但是仍旧希望能够单独发布笔画分离ps档以方便改作使用。

考慮到部分人士要求提供使用特定字形標準為默認字圖的分流版本，下版本起将直接開源筆画分離源文件以方便他人進行後續改作。

**Comment by NightFurySL2001** [comment]
非常感谢。

**Comment by ChiuMing-Neko** [comment]
已釋出。
