### ISSUE TITLE
有制作根据一点明体及局部异体统一版本的兴趣吗？

### ISSUE THREAD

**Issue by Scratchbin** [ChiuMing-Neko/ChiuKongGothic#5]
如题。

*（标题所说“局部异体统一”指对被 Unicode 以多字收录但实际应统一为单字者以映射 (References) 处理。）
另外我有以一点明体为基础为中国大陆简体字使用做出优化的版本（当然是因为当时那万恶的收字方式）。*

**Comment by ChiuMing-Neko** [comment]
Close
本專案不受理任何提議要求統合源規格分離原則分別編碼的字符。
